logging:
  level:
    org.springframework: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry-server:8761/eureka/

spring:
  rabbitmq:
    host: rabbitmq