logging:
  level:
    org.springframework: INFO

spring:
  data:
    mongodb:
      host: product-mongodb
      username: user
      password: password123
      database: ecommerce-db
      port: 27017

server:
  context-path: /products
  port: 6000
