logging:
  level:
    org.springframework: ERROR

#security:
#  oauth2:
#    client:
#      clientId: product-microservice
#      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
#      accessTokenUri: http://auth-server:5000/uaa/oauth/token
#      grant-type: client_credentials
#      scope: server

spring:
  data:
    mongodb:
      host: product-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: ecommerce-db
      port: 27017

server:
  context-path: /products
  port: 6000
